/*
 * This file is part of OpenModelica.
 *
 * Copyright (c) 1998-2014, Open Source Modelica Consortium (OSMC),
 * c/o Linköpings universitet, Department of Computer and Information Science,
 * SE-58183 Linköping, Sweden.
 *
 * All rights reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF GPL VERSION 3 LICENSE OR
 * THIS OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.2.
 * ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES
 * RECIPIENT'S ACCEPTANCE OF THE OSMC PUBLIC LICENSE OR THE GPL VERSION 3,
 * ACCORDING TO RECIPIENTS CHOICE.
 *
 * The OpenModelica software and the Open Source Modelica
 * Consortium (OSMC) Public License (OSMC-PL) are obtained
 * from OSMC, either from the above address,
 * from the URLs: http://www.ida.liu.se/projects/OpenModelica or
 * http://www.openmodelica.org, and in the OpenModelica distribution.
 * GNU version 3 is obtained from: http://www.gnu.org/copyleft/gpl.html.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without
 * even the implied warranty of  MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE, EXCEPT AS EXPRESSLY SET FORTH
 * IN THE BY RECIPIENT SELECTED SUBSIDIARY LICENSE CONDITIONS OF OSMC-PL.
 *
 * See the full OSMC Public License conditions for more details.
 *
 */

package CodegenOMSIC
" file:        CodegenOMSIC.tpl
  package:     CodegenOMSIC
  description: Code generation using Susan templates for 
               OpenModelica Simulation Inferface (OMSI) for C
"



import interface SimCodeTV;
import interface SimCodeBackendTV;
import CodegenUtil;
import CodegenUtilSimulation;
import CodegenEquations;
import CodegenOMSI_common.*;
import CodegenFMU;
import CodegenFMU2;

template translateModel(SimCode simCode, String FMUVersion, String FMUType)
" main entry point for OMSIC code generator"
::=
  match simCode
    case SIMCODE(__) then
    let guid = getUUIDStr()
    let () = textFile( createMakefile(), '<%fileNamePrefix%>_FMU.makefile')
    let () = textFile( CodegenFMU2.fmiModelDescription(simCode, guid, FMUType), 'modelDescription.xml')
    let () = textFile( generateOMSICHeader(simCode), '<%fileNamePrefix%>_omsic.h')
    let () = textFile( generateOMSIC(simCode), '<%fileNamePrefix%>_omsic.c')
    let () = textFile( CodegenEquations.generateEquationFiles(allEquations, fileNamePrefix), '<%fileNamePrefix%>_eqns.c')
    let () = textFile( CodegenEquations.generateEquationFilesHeader(allEquations, fileNamePrefix), '<%fileNamePrefix%>_eqns.h')
    <<>>
end translateModel;


template generateOMSIC(SimCode simCode)
"Generates main entry point for omsi wrapper functions for FMI"
::=
  match simCode
    case SIMCODE(modelInfo=MODELINFO(functions=functions, varInfo=varInfo as VARINFO(__))) then
    let modelNamePrefixStr = CodegenUtilSimulation.modelNamePrefix(simCode)
    <<
    <%insertCopyrightOpenModelica()%>

    #include"<%fileNamePrefix%>_omsic.h"
    #include"osi_fmi2_wrapper.h"

    /* Simulation code for <%CodegenUtil.dotPath(modelInfo.name)%> generated by the OpenModelica Compiler <%getVersionNr()%>. */
    // translated model <%fileNamePrefix%> to OMSIC <%\n%>

    /* Read input data from xml file */
    omsi_int <%CodegenUtil.symbolName(modelNamePrefixStr,"setupInputData")%> (omsi_t *omsi_data){

      <%generateSetupSimulationDataFunction(simCode, modelNamePrefixStr)%>

      return omsi_ok;
    }
    >>
end generateOMSIC;


template generateOMSICHeader(SimCode simCode)
"Generates header file for omsic.c"
::=
  let modelNamePrefixStr = CodegenUtilSimulation.modelNamePrefix(simCode)
  match simCode
  case SIMCODE(modelInfo=MODELINFO(__)) then
    <<
    <%insertCopyrightOpenModelica()%>

    /* Simulation code for <%CodegenUtil.dotPath(modelInfo.name)%> generated by the OpenModelica Compiler <%getVersionNr()%>. */
    #if !defined(<%modelNamePrefixStr%>__MODEL_H)
    #define <%modelNamePrefixStr%>__MODEL_H

    #include "omsi.h"
    #include "<%fileNamePrefix%>_omsic.h"

    /* Equation functions prototypes */
    #if defined(__cplusplus)
    extern "C" {
    #endif

    omsi_int <%CodegenUtil.symbolName(modelNamePrefixStr,"setupInputData")%> (omsi_t *omsi_data);

    #if defined(__cplusplus)
    }
    #endif

    #endif
    >>
  end match
end generateOMSICHeader;


template createMakefile()
::=
  <<
  # Makefile generated by OpenModelica


  build_fmu: build_OMSI_dll




  >>
end createMakefile;


annotation(__OpenModelica_Interface="backend");
end CodegenOMSIC;